### ISSUE TITLE
IPTables rule for redirect is not persistent.

### ISSUE THREAD

**Issue by evasil** [jelastic-jps/odoo#11]
Hello,

we have just found the issue with this Odoo JPS.

It only works as it should when just installed.
However, after restarting the Environment (or Stop/Start) Odoo not working throwing error 502.

Nginx cannot connect to a backend on port 80 (not sure why port 80, but ok).

After checking the JPS file we have found that there is a command which redirects port 80 to 8069:

`iptables -t nat -A PREROUTING -p tcp -m tcp --dport 80 -m comment --comment "Jelastic HTTP Autoredirect" -j REDIRECT --to-ports 8069`

This is not a persistent iptables rule and it disappears after Env or AppServer reboot.

I believe there are 2 ways to fix it:

1. Change Nginx config to speak to backend on proper port 8069, then one doesn't need IPtables redirection.
2. Or save IPtables rule into any startup script (/etc/rc.local or any other)

Thank you.

**Comment by lazarenkoalexey** [comment]
Thank you a lot for the found issue.
The command _iptables-save_ was added while the _install_ action.
We have published it in the Jelastic marketplace. Please check it on your side on a new JPS installataion
